provider:
  default:
    language: 0.34
    
deps: 
  - libatomic

binaries:
  - web
 
sources:
  - "**/*.pony"

cloud:
  config:
    package_update: true
    
    runcmd:
      # Disable cloud-init to avoid re-run on reboot
      - systemctl disable cloud-init

      # Enable web so as application is started at startup
      - systemctl enable web

# SystemD startup script
# This need to be tuned
# For security (do not run as root) ...
service: |
  [Unit]
  Description=web
  After=network.target

  [Service]
  Type=simple
  EnvironmentFile=/etc/web
  WorkingDirectory=/opt/web
  ExecStart=/opt/web/web

  [Install]
  WantedBy=multi-user.target
